### ISSUE TITLE
Unneeded repetition in src/arch/x86_64/syscall.asm

### ISSUE THREAD

**Issue by AnantTiwari-Naman** [MandelbrotOS/MandelbrotOS#47]
In syscall.asm, we have a macro:

```
>%macro pusha_no_rax 0  push rbx  push rcx  push rdx  push rbp  push rsi  push rdi  push rsp  push r8  push r9  push r10  push r11  push r12  push r13  push r14  push r15%endmacro
```

Why not push all the registers using ```pusha``` and then ```pop rax```?

**Comment by segfaultdev** [comment]
x86_64 does not have a `pusha` instruction, but even if we used the macro in interrupts.asm for it, it wouldn't work because rax is not pushed at the end and `pop rax` would actually pop r15 into rax, something we surely don't want because we need rax to not be pushed(and popped later) into the stack.

Just one thing though, that syscall code was just an example I made for testing purposes, and we plan on replacing it with something better. The thing is, we have been working in other projects in the Discord server and not worked on MandelbrotOS for a bit, but it's not abandoned. I also invite you to join the Discord server, if you want and you are not there yet: [https://discord.gg/W523cD3Q3P](https://discord.gg/W523cD3Q3P).
