### ISSUE TITLE
python support?

### ISSUE THREAD

**Issue by 17lwinn** [MandelbrotOS/MandelbrotOS#81]
hi- is there any plans to perhaps port python to the OS?

**Comment by CaydendW** [comment]
Have you done any work in OSDEV before? To put it simply: Python is a massive pipedream that will likely never happen. It's a massive task and needs quite a bit of functionality. I don't even have enough to port GCC which is a big job but much more accomplishable. 

Python isn't on my mind just because it's a long shot. Maybe one day, but it's *very* unlikely it will ever happen

**Comment by xhci1** [comment]
No porting Python would be like a death sentence.

**Comment by ichbluu** [comment]
there isn't even a working shell as far as I know, why would python support come before that?

**Comment by segfaultdev** [comment]
the main problem isn't it being hard or it requiring a shell or anything, it's python being something we shouldn't even need to port, as python is a slow language with a poorly designed syntax and a way too complex package system.
